# Generated by Django 5.2.12 on 2026-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='estimated_affected_area',
            field=models.FloatField(blank=True, help_text='Estimated affected area in square kilometers', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='estimated_affected_population',
            field=models.IntegerField(blank=True, help_text='Estimated number of affected people', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='incidents/images/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='relief_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated relief amount in USD', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the disaster', max_length=16),
        ),
        migrations.AddField(
            model_name='incident',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='incidents/videos/'),
        ),
    ]
