# Generated by Django 5.2.11 on 2026-05-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_api', '0002_incident_estimated_affected_area_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-detected_at'], name='incident_detected_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type'], name='incident_type_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity'], name='incident_severity_idx'),
        ),
    ]
